# Generated by Django 6.0.2 on 2026-02-15 18:46

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="attendancerecord",
            managers=[
                ("domain", django.db.models.manager.Manager()),
            ],
        ),
    ]
