# Generated by Django 6.0.2 on 2026-02-11 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RulesConfigVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                ("version", models.PositiveIntegerField(db_index=True, unique=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("bootstrap", "Bootstrap"),
                            ("update", "Update"),
                            ("rollback", "Rollback"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("diff", models.JSONField(blank=True, default=dict)),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="rules.rulesconfigversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RulesConfigState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                ("singleton", models.BooleanField(default=True, unique=True)),
                ("cache_key", models.CharField(db_index=True, max_length=64)),
                (
                    "active_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rules.rulesconfigversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="rulesconfigversion",
            index=models.Index(
                fields=["action", "created_at"], name="rules_rules_action_c16d2e_idx"
            ),
        ),
    ]
