# Generated by Django 6.0.2 on 2026-02-11 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollMonthly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                ("month", models.DateField(db_index=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("closed", "Closed"),
                            ("approved", "Approved"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rules_snapshot", models.JSONField(blank=True, default=dict)),
                ("total_raw_xp", models.IntegerField(default=0)),
                ("total_paid_xp", models.PositiveIntegerField(default=0)),
                ("total_fix_salary", models.PositiveBigIntegerField(default=0)),
                ("total_bonus_amount", models.PositiveBigIntegerField(default=0)),
                ("total_allowance_amount", models.PositiveBigIntegerField(default=0)),
                ("total_payout_amount", models.PositiveBigIntegerField(default=0)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_approved_months",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payroll_closed_months",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollMonthlyLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "L1"), (2, "L2"), (3, "L3"), (4, "L4"), (5, "L5")]
                    ),
                ),
                ("raw_xp", models.IntegerField(default=0)),
                ("paid_xp", models.PositiveIntegerField(default=0)),
                ("paid_xp_cap", models.PositiveIntegerField(default=0)),
                ("fix_salary", models.PositiveBigIntegerField(default=0)),
                ("allowance_amount", models.PositiveBigIntegerField(default=0)),
                ("bonus_rate", models.PositiveIntegerField(default=0)),
                ("bonus_amount", models.PositiveBigIntegerField(default=0)),
                ("total_amount", models.PositiveBigIntegerField(default=0)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "payroll_monthly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payroll.payrollmonthly",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_monthly_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="payrollmonthly",
            index=models.Index(
                fields=["status", "month"], name="payroll_pay_status_bfb40d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollmonthlyline",
            index=models.Index(
                fields=["payroll_monthly", "user"],
                name="payroll_pay_payroll_a73104_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollmonthlyline",
            index=models.Index(
                fields=["user", "created_at"], name="payroll_pay_user_id_23376a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollmonthlyline",
            constraint=models.UniqueConstraint(
                fields=("payroll_monthly", "user"),
                name="unique_payroll_monthly_line_per_user",
            ),
        ),
    ]
