# Generated by Django 6.0.2 on 2026-02-13 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollAllowanceGateDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("keep_gated", "Keep Gated"),
                            ("release_allowances", "Release Allowances"),
                        ],
                        max_length=30,
                    ),
                ),
                ("affected_lines_count", models.PositiveIntegerField(default=0)),
                ("total_allowance_delta", models.BigIntegerField(default=0)),
                ("note", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_monthly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowance_gate_decisions",
                        to="payroll.payrollmonthly",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["payroll_monthly", "created_at"],
                        name="payroll_pay_payroll_1b114c_idx",
                    ),
                    models.Index(
                        fields=["decision", "created_at"],
                        name="payroll_pay_decisio_35e1d0_idx",
                    ),
                ],
            },
        ),
    ]
