# Generated by Django 6.0.2 on 2026-02-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_role_telegramprofile_userrole_user_roles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "L1"), (2, "L2"), (3, "L3"), (4, "L4"), (5, "L5")],
                db_index=True,
                default=1,
            ),
        ),
    ]
