# Generated by Django 6.0.2 on 2026-02-15 18:46

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_user_level"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="accessrequest",
            managers=[
                ("domain", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="telegramprofile",
            managers=[
                ("domain", django.db.models.manager.Manager()),
            ],
        ),
    ]
