# Generated by Django 6.0.2 on 2026-02-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_accessrequest_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="patronymic",
        ),
    ]
