# Generated by Django 6.0.2 on 2026-02-11 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bike", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("srt_total_minutes", models.PositiveIntegerField(default=0)),
                ("flag_minutes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("waiting_qc", "Waiting QC"),
                            ("rework", "Rework"),
                            ("done", "Done"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bike",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="bike.bike",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="ticket_tick_status_0609ec_idx",
                    ),
                    models.Index(
                        fields=["technician", "status"],
                        name="ticket_tick_technic_755584_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            (
                                "status__in",
                                [
                                    "new",
                                    "assigned",
                                    "in_progress",
                                    "waiting_qc",
                                    "rework",
                                ],
                            ),
                        ),
                        fields=("bike",),
                        name="unique_active_ticket_per_bike",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            ("status", "in_progress"),
                            ("technician__isnull", False),
                        ),
                        fields=("technician",),
                        name="unique_in_progress_ticket_per_technician",
                    ),
                ],
            },
        ),
    ]
