# Generated by Django 6.0.2 on 2026-02-11 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("active_seconds", models.PositiveIntegerField(default=0)),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_sessions",
                        to="ticket.ticket",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticket", "status"],
                        name="ticket_work_ticket__83d57e_idx",
                    ),
                    models.Index(
                        fields=["technician", "status"],
                        name="ticket_work_technic_7f6c38_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            ("status__in", ["running", "paused"]),
                        ),
                        fields=("ticket",),
                        name="unique_open_work_session_per_ticket",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            ("status__in", ["running", "paused"]),
                        ),
                        fields=("technician",),
                        name="unique_open_work_session_per_technician",
                    ),
                ],
            },
        ),
    ]
