# Generated by Django 6.0.2 on 2026-02-11 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0002_worksession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("waiting_qc", "Waiting QC"),
                            ("rework", "Rework"),
                            ("done", "Done"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("waiting_qc", "Waiting QC"),
                            ("rework", "Rework"),
                            ("done", "Done"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("assigned", "Assigned"),
                            ("started", "Started"),
                            ("to_waiting_qc", "To Waiting QC"),
                            ("qc_pass", "QC Pass"),
                            ("qc_fail", "QC Fail"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="ticket.ticket",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticket", "created_at"],
                        name="ticket_tick_ticket__2ae70e_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="ticket_tick_action_87099d_idx",
                    ),
                ],
            },
        ),
    ]
