# Generated by Django 6.0.2 on 2026-02-11 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_tickettransition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSessionTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("paused", "Paused"),
                            ("resumed", "Resumed"),
                            ("stopped", "Stopped"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("event_at", models.DateTimeField(db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_session_transitions",
                        to="ticket.ticket",
                    ),
                ),
                (
                    "work_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="ticket.worksession",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["work_session", "event_at"],
                        name="ticket_work_work_se_88af7a_idx",
                    ),
                    models.Index(
                        fields=["ticket", "event_at"],
                        name="ticket_work_ticket__009234_idx",
                    ),
                    models.Index(
                        fields=["action", "event_at"],
                        name="ticket_work_action_98388d_idx",
                    ),
                ],
            },
        ),
    ]
