# Generated by Django 6.0.2 on 2026-02-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0005_ticket_checklist_snapshot_ticket_srt_approved_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockoutIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("ready_count_at_start", models.PositiveIntegerField(default=0)),
                (
                    "ready_count_at_end",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active", "started_at"],
                        name="ticket_stoc_is_acti_50ffb4_idx",
                    ),
                    models.Index(
                        fields=["started_at", "ended_at"],
                        name="ticket_stoc_started_fcae8d_idx",
                    ),
                ],
            },
        ),
    ]
