# Generated by Django 6.0.2 on 2026-02-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0006_stockoutincident"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLAAutomationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                ("rule_key", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("triggered", "Triggered"), ("resolved", "Resolved")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Warning"), ("critical", "Critical")],
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("metric_value", models.FloatField(default=0)),
                ("threshold_value", models.FloatField(default=0)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["rule_key", "created_at"],
                        name="ticket_slaa_rule_ke_9fb2ef_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="ticket_slaa_status_2e7c3b_idx",
                    ),
                ],
            },
        ),
    ]
