# Generated by Django 6.0.2 on 2026-02-13 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0007_slaautomationevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLAAutomationDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("delivered", models.BooleanField(db_index=True, default=False)),
                ("should_retry", models.BooleanField(db_index=True, default=False)),
                ("retry_backoff_seconds", models.PositiveIntegerField(default=0)),
                ("task_id", models.CharField(blank=True, default="", max_length=128)),
                ("reason", models.CharField(blank=True, default="", max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="ticket.slaautomationevent",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"],
                        name="ticket_slaa_event_i_54b874_idx",
                    ),
                    models.Index(
                        fields=["event", "attempt_number"],
                        name="ticket_slaa_event_i_34b2cb_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="ticket_slaa_status_30d495_idx",
                    ),
                ],
            },
        ),
    ]
