# Generated by Django 6.0.2 on 2026-02-15 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("ticket", "0008_slaautomationdeliveryattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="flag_color",
            field=models.CharField(
                choices=[
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("red", "Red"),
                    ("black", "Black"),
                    ("black_plus", "Black Plus"),
                ],
                db_index=True,
                default="green",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_manual",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="xp_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("under_review", "Under Review"),
                    ("new", "New"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("waiting_qc", "Waiting QC"),
                    ("rework", "Rework"),
                    ("done", "Done"),
                ],
                db_index=True,
                default="under_review",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TicketPartSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                            ("black", "Black"),
                            ("black_plus", "Black Plus"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("minutes", models.PositiveIntegerField(default=0)),
                (
                    "inventory_item_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_specs",
                        to="inventory.inventoryitempart",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_specs",
                        to="ticket.ticket",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticket", "inventory_item_part"],
                        name="ticket_tick_ticket__e64d6c_idx",
                    ),
                    models.Index(
                        fields=["ticket", "color"],
                        name="ticket_tick_ticket__235363_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("ticket", "inventory_item_part"),
                        name="unique_ticket_part_spec_per_part",
                    )
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_active_ticket_per_inventory_item",
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    (
                        "status__in",
                        [
                            "under_review",
                            "new",
                            "assigned",
                            "in_progress",
                            "waiting_qc",
                            "rework",
                        ],
                    ),
                ),
                fields=("inventory_item",),
                name="unique_active_ticket_per_inventory_item",
            ),
        ),
        migrations.AlterField(
            model_name="tickettransition",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_review", "Under Review"),
                    ("new", "New"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("waiting_qc", "Waiting QC"),
                    ("rework", "Rework"),
                    ("done", "Done"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tickettransition",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("under_review", "Under Review"),
                    ("new", "New"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("waiting_qc", "Waiting QC"),
                    ("rework", "Rework"),
                    ("done", "Done"),
                ],
                max_length=20,
            ),
        ),
    ]
