# Generated by Django 6.0.2 on 2026-02-15 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0009_ticket_review_manual_metrics_and_parts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="srt_approved_at",
            new_name="approved_at",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="srt_approved_by",
            new_name="approved_by",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="done_at",
            new_name="finished_at",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="srt_total_minutes",
            new_name="total_duration",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="checklist_snapshot",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="flag_color",
            field=models.CharField(
                choices=[("green", "Green"), ("yellow", "Yellow"), ("red", "Red")],
                db_index=True,
                default="green",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticketpartspec",
            name="color",
            field=models.CharField(
                choices=[("green", "Green"), ("yellow", "Yellow"), ("red", "Red")],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
