# Generated by Django 6.0.2 on 2026-02-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0010_alter_slaautomationdeliveryattempt_managers_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="slaautomationdeliveryattempt",
            name="ticket_slaa_event_i_54b874_idx",
        ),
        migrations.RemoveIndex(
            model_name="slaautomationdeliveryattempt",
            name="ticket_slaa_event_i_34b2cb_idx",
        ),
        migrations.RemoveIndex(
            model_name="slaautomationdeliveryattempt",
            name="ticket_slaa_status_30d495_idx",
        ),
        migrations.RemoveIndex(
            model_name="slaautomationevent",
            name="ticket_slaa_rule_ke_9fb2ef_idx",
        ),
        migrations.RemoveIndex(
            model_name="slaautomationevent",
            name="ticket_slaa_status_2e7c3b_idx",
        ),
        migrations.DeleteModel(
            name="SLAAutomationDeliveryAttempt",
        ),
        migrations.DeleteModel(
            name="SLAAutomationEvent",
        ),
    ]
