# Generated by Django 6.0.2 on 2026-02-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ticket",
            "0011_remove_slaautomationdeliveryattempt_ticket_slaa_event_i_54b874_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stockoutincident",
            name="ticket_stoc_is_acti_50ffb4_idx",
        ),
        migrations.RemoveIndex(
            model_name="stockoutincident",
            name="ticket_stoc_started_fcae8d_idx",
        ),
        migrations.DeleteModel(
            name="StockoutIncident",
        ),
    ]
