# Generated by Django 6.0.2 on 2026-02-15 18:46

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ticket",
            "0012_remove_stockoutincident_ticket_stoc_is_acti_50ffb4_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="ticket",
            managers=[
                ("domain", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tickettransition",
            managers=[
                ("domain", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="worksession",
            managers=[
                ("domain", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="worksessiontransition",
            managers=[
                ("domain", django.db.models.manager.Manager()),
            ],
        ),
    ]
