# Generated by Django 6.0.2 on 2026-02-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0013_alter_ticket_managers_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_in_progress_ticket_per_technician",
        ),
    ]
