# Generated by Django 6.0.2 on 2026-03-03 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0014_remove_ticket_unique_in_progress_ticket_per_technician"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("under_review", "Under Review"),
                    ("new", "New"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("waiting_qc", "Waiting QC"),
                    ("rework", "Rework"),
                    ("done", "Done"),
                ],
                db_index=True,
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticketpartspec",
            name="completed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketpartspec",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_ticket_part_specs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketpartspec",
            name="completion_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticketpartspec",
            name="is_completed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="ticketpartspec",
            name="needs_rework",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="ticketpartspec",
            name="rework_for_technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_part_rework_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TicketPartCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Updated At",
                    ),
                ),
                ("completed_at", models.DateTimeField(db_index=True)),
                ("note", models.TextField(blank=True, default="")),
                ("is_rework", models.BooleanField(db_index=True, default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source_qc_fail_transition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rework_part_completions",
                        to="ticket.tickettransition",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_completions",
                        to="ticket.ticket",
                    ),
                ),
                (
                    "ticket_part_spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_history",
                        to="ticket.ticketpartspec",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticket", "completed_at"],
                        name="tick_partcomp_ticket_at_idx",
                    ),
                    models.Index(
                        fields=["ticket_part_spec", "completed_at"],
                        name="tick_partcomp_spec_at_idx",
                    ),
                    models.Index(
                        fields=["technician", "completed_at"],
                        name="tick_partcomp_tech_at_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TicketPartQCFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name="Updated At",
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "qc_fail_transition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failed_part_mappings",
                        to="ticket.tickettransition",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_qc_failures",
                        to="ticket.ticket",
                    ),
                ),
                (
                    "ticket_part_completion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ticket.ticketpartcompletion",
                    ),
                ),
                (
                    "ticket_part_spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_failure_history",
                        to="ticket.ticketpartspec",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticket", "created_at"],
                        name="tick_partfail_ticket_at_idx",
                    ),
                    models.Index(
                        fields=["ticket_part_spec", "created_at"],
                        name="tick_partfail_spec_at_idx",
                    ),
                    models.Index(
                        fields=["technician", "created_at"],
                        name="tick_partfail_tech_at_idx",
                    ),
                ],
            },
        ),
        migrations.AlterField(
            model_name="tickettransition",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("claimed", "Claimed"),
                    ("assigned", "Assigned"),
                    ("started", "Started"),
                    ("parts_completed", "Parts Completed"),
                    ("to_waiting_qc", "To Waiting QC"),
                    ("qc_pass", "QC Pass"),
                    ("qc_fail", "QC Fail"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
