# Generated by Django 6.0.2 on 2026-02-16 09:40

from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models


def migrate_inventory_item_parts_to_fk(apps, schema_editor):
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    InventoryItemPart = apps.get_model("inventory", "InventoryItemPart")
    TicketPartSpec = apps.get_model("ticket", "TicketPartSpec")

    through_model = InventoryItem.parts.through

    item_fk_name = None
    part_fk_name = None
    for field in through_model._meta.fields:
        remote_model = getattr(getattr(field, "remote_field", None), "model", None)
        remote_label = getattr(getattr(remote_model, "_meta", None), "label_lower", "")
        if remote_label == "inventory.inventoryitem":
            item_fk_name = field.name
        if remote_label == "inventory.inventoryitempart":
            part_fk_name = field.name

    if item_fk_name is None or part_fk_name is None:
        raise RuntimeError(
            "Unable to resolve inventory-item part through table fields."
        )

    linked_item_ids_by_part_id: dict[int, list[int]] = defaultdict(list)
    for part_id, item_id in through_model._base_manager.order_by(
        part_fk_name,
        item_fk_name,
    ).values_list(part_fk_name, item_fk_name):
        linked_item_ids_by_part_id[int(part_id)].append(int(item_id))

    for part in InventoryItemPart._base_manager.order_by("id").iterator():
        raw_item_ids = linked_item_ids_by_part_id.get(part.id, [])

        if not raw_item_ids:
            raw_item_ids = list(
                TicketPartSpec._base_manager.filter(inventory_item_part_id=part.id)
                .order_by("ticket__inventory_item_id")
                .values_list("ticket__inventory_item_id", flat=True)
                .distinct()
            )

        item_ids: list[int] = []
        seen_item_ids: set[int] = set()
        for item_id in raw_item_ids:
            normalized_item_id = int(item_id)
            if normalized_item_id in seen_item_ids:
                continue
            seen_item_ids.add(normalized_item_id)
            item_ids.append(normalized_item_id)

        if not item_ids:
            continue

        part.inventory_item_id = item_ids[0]
        part.save(update_fields=["inventory_item"])

        for item_id in item_ids[1:]:
            cloned_part = InventoryItemPart._base_manager.create(
                inventory_item_id=item_id,
                name=part.name,
                deleted_at=part.deleted_at,
            )
            TicketPartSpec._base_manager.filter(
                inventory_item_part_id=part.id,
                ticket__inventory_item_id=item_id,
            ).update(inventory_item_part_id=cloned_part.id)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventory_managers_and_more"),
        ("ticket", "0013_alter_ticket_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitempart",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_parts",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitempart",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(
            migrate_inventory_item_parts_to_fk,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="parts",
        ),
        migrations.AlterField(
            model_name="inventoryitempart",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitempart",
            index=models.Index(
                fields=["inventory_item", "name"],
                name="inv_item_part_item_name_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitempart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("inventory_item", "name"),
                name="inv_item_part_unique_name_per_item",
            ),
        ),
    ]
