# Generated by Codex on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_part_category(apps, schema_editor):
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    InventoryItemPart = apps.get_model("inventory", "InventoryItemPart")

    item_category_by_id = dict(
        InventoryItem._base_manager.values_list("id", "category_id")
    )

    for part in InventoryItemPart._base_manager.order_by("id").iterator():
        if part.category_id is not None:
            continue
        part.category_id = item_category_by_id.get(part.inventory_item_id)
        part.save(update_fields=["category"])


def deduplicate_category_parts(apps, schema_editor):
    InventoryItemPart = apps.get_model("inventory", "InventoryItemPart")
    TicketPartSpec = apps.get_model("ticket", "TicketPartSpec")

    canonical_part_id_by_key: dict[tuple[int, str], int] = {}
    now = timezone.now()

    queryset = InventoryItemPart._base_manager.filter(
        deleted_at__isnull=True,
        category_id__isnull=False,
    ).order_by("id")
    for part in queryset.iterator():
        normalized_name = (part.name or "").strip().lower()
        key = (int(part.category_id), normalized_name)
        canonical_part_id = canonical_part_id_by_key.get(key)
        if canonical_part_id is None:
            canonical_part_id_by_key[key] = int(part.id)
            continue

        active_specs = TicketPartSpec._base_manager.filter(
            inventory_item_part_id=part.id,
            deleted_at__isnull=True,
        )
        for spec in active_specs.iterator():
            duplicate_exists = TicketPartSpec._base_manager.filter(
                ticket_id=spec.ticket_id,
                inventory_item_part_id=canonical_part_id,
                deleted_at__isnull=True,
            ).exists()
            if duplicate_exists:
                spec.deleted_at = now
                spec.save(update_fields=["deleted_at"])
            else:
                spec.inventory_item_part_id = canonical_part_id
                spec.save(update_fields=["inventory_item_part"])

        TicketPartSpec._base_manager.filter(
            inventory_item_part_id=part.id,
            deleted_at__isnull=False,
        ).update(inventory_item_part_id=canonical_part_id)

        part.deleted_at = now
        part.save(update_fields=["deleted_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_inventoryitem_parts_and_more"),
        ("ticket", "0014_remove_ticket_unique_in_progress_ticket_per_technician"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitempart",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parts",
                to="inventory.inventoryitemcategory",
            ),
        ),
        migrations.RunPython(backfill_part_category, migrations.RunPython.noop),
        migrations.RunPython(deduplicate_category_parts, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="inventoryitempart",
            index=models.Index(
                fields=["category", "name"],
                name="inv_item_part_cat_name_idx",
            ),
        ),
    ]
