# Generated by Django 6.0.2 on 2026-02-11 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="XPLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("attendance_punctuality", "Attendance Punctuality")],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="xp_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="gamificatio_user_id_5ee307_idx",
                    ),
                    models.Index(
                        fields=["entry_type", "created_at"],
                        name="gamificatio_entry_t_24aac9_idx",
                    ),
                ],
            },
        ),
    ]
