# Generated by Django 6.0.2 on 2026-02-12 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0002_alter_xpledger_entry_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyLevelEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                ("week_start", models.DateField(db_index=True)),
                ("week_end", models.DateField(db_index=True)),
                ("raw_xp", models.IntegerField(default=0)),
                (
                    "previous_level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "L1"), (2, "L2"), (3, "L3"), (4, "L4"), (5, "L5")]
                    ),
                ),
                (
                    "new_level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "L1"), (2, "L2"), (3, "L3"), (4, "L4"), (5, "L5")]
                    ),
                ),
                ("is_level_up", models.BooleanField(default=False)),
                ("rules_version", models.PositiveIntegerField(default=1)),
                (
                    "rules_cache_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_level_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LevelUpCouponEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                ("week_start", models.DateField(db_index=True)),
                ("amount", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="UZS", max_length=10)),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="level_up_coupon_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupon_event",
                        to="gamification.weeklylevelevaluation",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="weeklylevelevaluation",
            index=models.Index(
                fields=["week_start", "user"], name="gamificatio_week_st_dcd7f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklylevelevaluation",
            index=models.Index(
                fields=["user", "created_at"], name="gamificatio_user_id_8659d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklylevelevaluation",
            index=models.Index(
                fields=["is_level_up", "week_start"],
                name="gamificatio_is_leve_55ab3f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklylevelevaluation",
            constraint=models.UniqueConstraint(
                fields=("user", "week_start"),
                name="unique_weekly_level_evaluation_per_user_week",
            ),
        ),
        migrations.AddIndex(
            model_name="levelupcouponevent",
            index=models.Index(
                fields=["user", "week_start"], name="gamificatio_user_id_30f1aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="levelupcouponevent",
            index=models.Index(
                fields=["week_start", "created_at"],
                name="gamificatio_week_st_4250e9_idx",
            ),
        ),
    ]
