# Generated by Django 6.0.2 on 2026-02-15 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0003_weeklylevelevaluation_levelupcouponevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="XPLedger",
            new_name="XPTransaction",
        ),
        migrations.AlterField(
            model_name="xptransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="xp_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameIndex(
            model_name="xptransaction",
            new_name="gamificatio_user_id_83437f_idx",
            old_name="gamificatio_user_id_5ee307_idx",
        ),
        migrations.RenameIndex(
            model_name="xptransaction",
            new_name="gamificatio_entry_t_ca3dda_idx",
            old_name="gamificatio_entry_t_24aac9_idx",
        ),
    ]
