# Generated by Django 6.0.2 on 2026-02-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0004_xptransaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xptransaction",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("attendance_punctuality", "Attendance Punctuality"),
                    ("ticket_base_xp", "Ticket Base XP"),
                    ("ticket_qc_first_pass_bonus", "Ticket QC First Pass Bonus"),
                    ("ticket_qc_status_update", "Ticket QC Status Update"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
