# Generated by Django 6.0.2 on 2026-02-17 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0005_alter_xptransaction_entry_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLevelHistoryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("weekly_evaluation", "Weekly Evaluation"),
                            ("manual_override", "Manual Override"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("status", models.CharField(db_index=True, max_length=40)),
                (
                    "previous_level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "L1"), (2, "L2"), (3, "L3"), (4, "L4"), (5, "L5")]
                    ),
                ),
                (
                    "new_level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "L1"), (2, "L2"), (3, "L3"), (4, "L4"), (5, "L5")]
                    ),
                ),
                ("warning_active_before", models.BooleanField(default=False)),
                ("warning_active_after", models.BooleanField(default=False)),
                ("week_start", models.DateField(blank=True, db_index=True, null=True)),
                ("week_end", models.DateField(blank=True, db_index=True, null=True)),
                ("reference", models.CharField(db_index=True, max_length=140, unique=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="level_history_events",
                        to="account.user",
                    ),
                ),
                (
                    "weekly_evaluation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="level_history_events",
                        to="gamification.weeklylevelevaluation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="gamificatio_user_id_530bfd_idx",
                    ),
                    models.Index(
                        fields=["user", "week_start"],
                        name="gamificatio_user_id_7f36a7_idx",
                    ),
                    models.Index(
                        fields=["source", "status", "created_at"],
                        name="gamificatio_source_aa3e6c_idx",
                    ),
                    models.Index(
                        fields=["warning_active_after", "created_at"],
                        name="gamificatio_warning_b7bf03_idx",
                    ),
                ],
            },
        ),
    ]
